CREATE TABLE `users` (
 `uid` varchar(36) NOT NULL,
 `email` varchar(100) DEFAULT NULL,
 `username` varchar(25) NOT NULL,
 `first_name` varchar(25) NOT NULL,
 `last_name` varchar(25) DEFAULT NULL,
 `password` varchar(100) NOT NULL,
 `avatar` varchar(200) DEFAULT NULL,
 `forgot_code` varchar(100) DEFAULT NULL,
 `last_login` int(13) DEFAULT '0',
 `address` varchar(100) DEFAULT NULL,
 `city` varchar(100) DEFAULT NULL,
 `state` varchar(100) DEFAULT NULL,
 `country` varchar(100) DEFAULT NULL,
 `zip` varchar(10) DEFAULT NULL,
 `phone_number` varchar(20) DEFAULT NULL,
 `deleted` tinyint(1) NOT NULL DEFAULT '0',
 `created` datetime NOT NULL,
 `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1